language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/   
matrix:
  allow_failures:
  - julia: nightly
env:
  - PYTHON=""
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ExcelReaders")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
